CREATE TABLE pTB_ROLE (
    id     INT IDENTITY(1,1) PRIMARY KEY,
    name   NVARCHAR(100),   -- EXECUTOR | SOLICITANTE | APROVADOR
    detail NVARCHAR(500),
    status NVARCHAR(50)     -- ATIVO | INATIVO
);
